openapi: 3.1.0
info:
  title: Authn Service API
  description: ''
  license:
    name: ''
  version: 1.0.0
servers:
- url: http://localhost:3000
  description: Development
paths:
  /v1/login:
    post:
      tags:
      - auth
      operationId: login
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/LoginRequest'
        required: true
      responses:
        '200':
          description: A successful login
          headers:
            Set-Cookie:
              schema:
                type: string
              description: Secure HTTP-only refresh_token session cookie; `Max-Age=604800`
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/AccessTokenResponse'
        '400':
          description: An invalid payload
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorResponse'
        '401':
          description: An invalid credentials
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorResponse'
        '403':
          description: A forbidden request
        '422':
          description: An unprocessable payload
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ValidationErrorResponse'
        '500':
          description: An internal failure
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorResponse'
  /v1/register:
    post:
      tags:
      - auth
      operationId: register
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/RegistrationRequest'
        required: true
      responses:
        '200':
          description: A successful registration
        '400':
          description: An invalid payload
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorResponse'
        '403':
          description: A forbidden request
        '409':
          description: A duplicate entity
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorResponse'
        '422':
          description: An unprocessable payload
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ValidationErrorResponse'
        '500':
          description: An internal failure
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorResponse'
components:
  schemas:
    AccessTokenResponse:
      type: object
      required:
      - access_token
      properties:
        access_token:
          type: string
    Error:
      type: string
      enum:
      - DB_INSERT_FAILED
      - DB_FETCH_FAILED
      - DB_UPDATE_FAILED
      - DB_DELETE_FAILED
      - DB_TRANSACTION_BEGIN_FAILED
      - DB_TRANSACTION_COMMIT_FAILED
      - PASSWORD_HASH_CONTEXT_FAILED
      - PASSWORD_HASH_ACTION_FAILED
      - TIME_GEN_FAILED
      - INVALID_GRANT
      - INVALID_CREDENTIALS
      - DUPLICATE_ENTITY
    ErrorResponse:
      type: object
      required:
      - error
      properties:
        error:
          $ref: '#/components/schemas/Error'
      examples:
      - '{"error": "DB_FETCH_FAILED"}'
    LoginRequest:
      type: object
      required:
      - email
      - password
      - device_name
      properties:
        device_name:
          type: string
          examples:
          - iPhone 18 Pro
          maxLength: 255
          minLength: 5
        email:
          type: string
          examples:
          - user@mail.com
        password:
          type: string
          examples:
          - P@ssword123!
          maxLength: 128
          minLength: 12
    RegistrationRequest:
      type: object
      required:
      - email
      - password
      - password_confirm
      properties:
        email:
          type: string
          examples:
          - user@mail.com
        password:
          type: string
          examples:
          - P@ssword123!
          maxLength: 128
          minLength: 12
        password_confirm:
          type: string
          examples:
          - P@ssword123!
          maxLength: 128
          minLength: 12
    ValidationErrorResponse:
      type: object
      required:
      - errors
      properties:
        errors:
          type: object
          additionalProperties:
            type: string
          propertyNames:
            type: string
      examples:
      - '{ "errors": { "image_url": "Must be a valid URL", "title": "Must be at least 1 character long" } }'
