version = 1

[schema]

[[schema.tables]]
id = 0
name = "books"
primary_key = { columns = [{ table = 0, index = 2 }], index = { table = 0, index = 0 } }

[[schema.tables.columns]]
id = { table = 0, index = 0 }
name = "created_at"
ty = "Timestamp"
storage_ty = { Timestamp = 6 }

[[schema.tables.columns]]
id = { table = 0, index = 1 }
name = "updated_at"
ty = "Timestamp"
storage_ty = { Timestamp = 6 }

[[schema.tables.columns]]
id = { table = 0, index = 2 }
name = "id"
ty = "Uuid"
storage_ty = "Uuid"

[[schema.tables.columns]]
id = { table = 0, index = 3 }
name = "published_date"
ty = "Date"
storage_ty = "Date"

[[schema.tables.columns]]
id = { table = 0, index = 4 }
name = "status"
ty = "U8"
storage_ty = { UnsignedInteger = 1 }

[[schema.tables.columns]]
id = { table = 0, index = 5 }
name = "title"
ty = "String"
storage_ty = "Text"

[[schema.tables.columns]]
id = { table = 0, index = 6 }
name = "description"
ty = "String"
storage_ty = "Text"
nullable = true

[[schema.tables.columns]]
id = { table = 0, index = 7 }
name = "image_url"
ty = "String"
storage_ty = "Text"
nullable = true

[[schema.tables.indices]]
id = { table = 0, index = 0 }
name = "index_books_by_id"
on = 0
columns = [{ column = { table = 0, index = 2 }, op = "Eq", scope = "Partition" }]
unique = true
primary_key = true

[[schema.tables]]
id = 1
name = "authors"
primary_key = { columns = [{ table = 1, index = 2 }], index = { table = 1, index = 0 } }

[[schema.tables.columns]]
id = { table = 1, index = 0 }
name = "created_at"
ty = "Timestamp"
storage_ty = { Timestamp = 6 }

[[schema.tables.columns]]
id = { table = 1, index = 1 }
name = "updated_at"
ty = "Timestamp"
storage_ty = { Timestamp = 6 }

[[schema.tables.columns]]
id = { table = 1, index = 2 }
name = "id"
ty = "Uuid"
storage_ty = "Uuid"

[[schema.tables.columns]]
id = { table = 1, index = 3 }
name = "name"
ty = "String"
storage_ty = "Text"

[[schema.tables.columns]]
id = { table = 1, index = 4 }
name = "description"
ty = "String"
storage_ty = "Text"
nullable = true

[[schema.tables.indices]]
id = { table = 1, index = 0 }
name = "index_authors_by_id"
on = 1
columns = [{ column = { table = 1, index = 2 }, op = "Eq", scope = "Partition" }]
unique = true
primary_key = true
